#!bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root. Terminated."
   exit 1
fi

#create directory for program
printf "\nCreating directory for PLX kernel objects . . ."
mkdir /var/local/plx


#plx9054 driver
printf "\ncopy files for plx9054 driver"
cp ../Driver/Plx9054/Plx9054.ko /var/local/plx
cp ./plx/Plx_load /var/local/plx
cp ./plx/Plx_unload /var/local/plx
cp ./plx/plx9054.conf /etc/modprobe.d

#plx9050 driver
printf "\ncopy files for plx9050 driver"
cp ../Driver/Plx9050/Plx9050.ko /var/local/plx
cp ./plx/plx9050.conf /etc/modprobe.d

#plx8311 driver
printf "\ncopy files for plx8311 driver"
cp ../Driver/Plx8311/Plx8311.ko /var/local/plx
cp ./plx/plx8311.conf /etc/modprobe.d


#register drivers in modprobe file
printf "\n\nRegister PLX driver in modprobe file . . ."
echo "plx9054" >> /etc/modules
echo "plx9050" >> /etc/modules
echo "plx8311" >> /etc/modules

exit 0

