#!bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root. Terminated."
   exit 1
fi

echo "Deleting driver"
rm /etc/udev/rules.d/50-rsh_devices.rules
rm /usr/local/bin/device_namer
rm /lib/modules/$(uname -r)/kernel/drivers/usb/rsh/lausb.ko
depmod -a

echo "Done! Please reboot."

exit 0

