Rsh API: G:/SDK2/HEADERS/Include/RshFunctions.cpp File Reference
RshFunctions.cpp File Reference
Global functions.
#include "RshFunctions.h"
#include "RshMacro.h"
#include <limits>
Macros
#define RSH_FUNCTIONS_CPP
Functions
U64 RshMix ()
Tries to get a unique number.
U64 RshMix (U64 seed)
Tries to get a unique number.
U32 RshCRC32 (U8 *buf, size_t len)
CRC32 calculation.
double RshRoundD (double val, double pre)
Round a double value with specified precision.
double RshLsbToVoltCoef (U32 gain, double range, U8 bitSize)
Calculate [LSB/volts] conversion coefficient.
double RshVoltToLsbCoef (U32 gain, double range, U8 bitSize)
Calculate [volts/LSB] conversion coefficient.
double RshLsbToVolt (double lsb, U32 gain, double range, U8 bitSize)
Convert LSB value to voltage value.
double RshVoltToLsb (double voltage, U32 gain, double range, U8 bitSize)
Convert voltage value to LSB value.
const wchar_t * RshConvertToUTF16 (const char *pStr)
Construct UTF-16 string from UTF-8 constant string.
template<typename T , RshDataTypes dataCode>
U32 RshCopyStringToBuffer (const char *str, RshBufferType< T, dataCode > &userBuffer)
Copy string to RSH_BUFFER_U8 or RSH_BUFFER_S8 buffer.
template<>
U32 RshCopyStringToBuffer (const char *str, RshBufferType< S8, rshBufferTypeS8 > &userBuffer)
template<>
U32 RshCopyStringToBuffer (const char *str, RshBufferType< U8, rshBufferTypeU8 > &userBuffer)
template<typename T , RshDataTypes dataCode>
U32 RshFillBufferWithRandomNumbers (RshBufferType< T, dataCode > &userBuffer, U32 seed)
Fill buffer with random numbers.
template<>
U32 RshFillBufferWithRandomNumbers< U8, rshBufferTypeU8 > (RshBufferType< U8, rshBufferTypeU8 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< S8, rshBufferTypeS8 > (RshBufferType< S8, rshBufferTypeS8 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< U16, rshBufferTypeU16 > (RshBufferType< U16, rshBufferTypeU16 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< S16, rshBufferTypeS16 > (RshBufferType< S16, rshBufferTypeS16 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< U32, rshBufferTypeU32 > (RshBufferType< U32, rshBufferTypeU32 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< S32, rshBufferTypeS32 > (RshBufferType< S32, rshBufferTypeS32 > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< double, rshBufferTypeDouble > (RshBufferType< double, rshBufferTypeDouble > &userBuffer, U32 seed)
template<>
U32 RshFillBufferWithRandomNumbers< float, rshBufferTypeFloat > (RshBufferType< float, rshBufferTypeFloat > &userBuffer, U32 seed)
Detailed Description
Global functions.
Copyright
JSC "Rudnev-Shilyaev"
Date
28.12.2015
Version
1.0 [SDK 2.1]
This file contains implementation of common functions used within RSH SDK code.
Macro Definition Documentation
#define RSH_FUNCTIONS_CPP
Function Documentation
const wchar_t* RshConvertToUTF16 (const char * pStr)
Construct UTF-16 string from UTF-8 constant string.
Convinience function used to initialize std::wstring values with string constants. When source file is coded to UTF-8 there some issues with cyrilic string constants that must be UTF-16 converted (at least in Windows). This function work over this issue
Parameters
[in] pStr UTF-8 encoded string
Returns
UTF-16 constant string
Warning
Current realisaion is a bit clumsy, use wchar_t buffer with size 1024 and replace data in it with every function call. So, result of the function can be used only to initialize other variables and not directly.
template<typename T , RshDataTypes dataCode> U32 RshCopyStringToBuffer (const char * str, RshBufferType< T, dataCode > & userBuffer)
Copy string to RSH_BUFFER_U8 or RSH_BUFFER_S8 buffer.
This function can be used to set buffer values from string. If buffer type differs from rshBufferTypeU8 or rshBufferTypeS8, error code will be returned
Parameters
[in] str String that will be copied to buffer. Must be NULL-terminated (strlen is used to determine size).
[in,out] userBuffer Buffer where data will be copied
Returns
RSH_API_SUCCESS or error code.
References RSH_API_PARAMETER_NOTSUPPORTED.
template<> U32 RshCopyStringToBuffer (const char * str, RshBufferType< S8, rshBufferTypeS8 > & userBuffer)
References RshBufferType< T, dataCode >::Copy(), NULL, RshBufferType< T, dataCode >::PSize(), RSH_API_PARAMETER_ZEROADDRESS, and RSH_API_SUCCESS.
template<> U32 RshCopyStringToBuffer (const char * str, RshBufferType< U8, rshBufferTypeU8 > & userBuffer)
References RshBufferType< T, dataCode >::Copy(), NULL, RshBufferType< T, dataCode >::PSize(), RSH_API_PARAMETER_ZEROADDRESS, and RSH_API_SUCCESS.
U32 RshCRC32 (U8 * buf, size_t len)
CRC32 calculation.
This function calculates crc32 value of given string.
Parameters
[in] buf Pointer to string buffer
[in] len How many symbols from buffer must be used in calculation
Returns
Calculated crc32 value or zero if input parameters are invalid.
template<typename T , RshDataTypes dataCode> U32 RshFillBufferWithRandomNumbers (RshBufferType< T, dataCode > & userBuffer, U32 seed = 0)
Fill buffer with random numbers.
Parameters
[in] seed Seed for std::srand() function. If no seed specified (or zero seed passed) random seed generated by RshMix() function will be used.
Buffer will be filled with random numbers, generated by std::rand() function. RshBufferType::Size() field will be equal to RshBufferType::PSize() after this method call.
See Also
RshMix()
Examples:
RshBufferType_STL_EN.cpp.
References RSH_API_PARAMETER_NOTSUPPORTED.
template<> U32 RshFillBufferWithRandomNumbers< double, rshBufferTypeDouble > (RshBufferType< double, rshBufferTypeDouble > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< float, rshBufferTypeFloat > (RshBufferType< float, rshBufferTypeFloat > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< S16, rshBufferTypeS16 > (RshBufferType< S16, rshBufferTypeS16 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< S32, rshBufferTypeS32 > (RshBufferType< S32, rshBufferTypeS32 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< S8, rshBufferTypeS8 > (RshBufferType< S8, rshBufferTypeS8 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< U16, rshBufferTypeU16 > (RshBufferType< U16, rshBufferTypeU16 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< U32, rshBufferTypeU32 > (RshBufferType< U32, rshBufferTypeU32 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
template<> U32 RshFillBufferWithRandomNumbers< U8, rshBufferTypeU8 > (RshBufferType< U8, rshBufferTypeU8 > & userBuffer, U32 seed)
References RSH_API_SUCCESS, and RshMix().
double RshLsbToVolt (double lsb, U32 gain, double range, U8 bitSize)
Convert LSB value to voltage value.
This function do reverse operation of RshVoltToLsb() function - convert LSB value to volts.
See Also
RshVoltToLsb()
References RshVoltToLsbCoef().
double RshLsbToVoltCoef (U32 gain, double range, U8 bitSize)
Calculate [LSB/volts] conversion coefficient.
This function calculates coefficient that can be used to convert data from voltage to LSB codes (or vice versa).
For example, if one need send signal buffer to GSPF, conversion coefficient can be calculated and then every item in data array (in volts) must be multipyed on that coefficient to produce valid buffer, that can be send to device.
Parameters
[in] gain Gain coefficient used by the device or channel we need coefficient for.
[in] range Maximum range in volts (for gain equal to 1). You can get this value using IRshDevice::Get() method with the RSH_GET_DEVICE_INPUT_RANGE_VOLTS to get max positive voltage and then multiplying it by 2 (to get full range).
[in] bitSize Bit number. This value determines LSB range. (range = 1<<bitSize) RshApi IRshDevice::GetData() method use data shifted to MSB, so one need pass 8, 16, or 32 as bitSize value, not ADC or DAC bits.
Returns
Coefficient that can be used to convert data from Volt to LSB (or vice versa)
Remarks
"LSB to volt" in function name means that calculated coefficient will have [LSB/Volt] unit, so you can actualy use it two ways - to convert from volts to LSB (need to multiply) or to convert from LSB to volts (need to devide).
References RSH_CMPDOUBLE.
Referenced by RshVoltToLsb().
U64 RshMix ()
Tries to get a unique number.
This function generates unique 64bit number using current clock, time and process id.
Returns
Generated unique number
References __rshgetpid, and NULL.
Referenced by RshFillBufferWithRandomNumbers< double, rshBufferTypeDouble >(), RshFillBufferWithRandomNumbers< float, rshBufferTypeFloat >(), RshFillBufferWithRandomNumbers< S16, rshBufferTypeS16 >(), RshFillBufferWithRandomNumbers< S32, rshBufferTypeS32 >(), RshFillBufferWithRandomNumbers< S8, rshBufferTypeS8 >(), RshFillBufferWithRandomNumbers< U16, rshBufferTypeU16 >(), RshFillBufferWithRandomNumbers< U32, rshBufferTypeU32 >(), and RshFillBufferWithRandomNumbers< U8, rshBufferTypeU8 >().
U64 RshMix (U64 seed)
Tries to get a unique number.
This function generates unique 64bit number using given seed. Generatied value depend on current time and process id also.
Parameters
[in] seed Source number
Returns
Generated unique number
References __rshgetpid, and NULL.
double RshRoundD (double value, double precision)
Round a double value with specified precision.
This function rounds given value to presicion.
For example, if one pass 3.14159 with precision=2, result will be 3.14
Parameters
[in] value Value to round
[in] precision Desired precision (digits after point)
Returns
Rounded doulbe value
double RshVoltToLsb (double voltage, U32 gain, double range, U8 bitSize)
Convert voltage value to LSB value.
This function convert input value in volts to corresponding value in LSB.
Parameters
[in] voltage Voltage value we need to convert
[in] gain Gain coefficient used by the device or channel we need coefficient for.
[in] range Maximum range in volts (for gain equal to 1). You can get this value using IRshDevice::Get() method with the RSH_GET_DEVICE_INPUT_RANGE_VOLTS to get max positive voltage and then multiplying it by 2 (to get full range).
[in] bitSize Bit number. This value determines LSB range. (range = 1<<bitSize) RshApi IRshDevice::GetData() method use data shifted to MSB, so one need pass 8, 16, or 32 as bitSize value, not ADC or DAC bits.
Returns
Corresponding value in LSB
Remarks
This function is convinient when one or two calculation need be performed. If you need convert big array of data, better use one of RshVoltToLsbCoef() or RshLsbToVoltCoef() functions and then multiply all array values on coefficient obtained.
References RshLsbToVoltCoef().
double RshVoltToLsbCoef (U32 gain, double range, U8 bitSize)
Calculate [volts/LSB] conversion coefficient.
This function is analog ot RshLsbToVoltCoef() function, the only differenct is that coefficient is reversed.
RshVoltToLsbCoef() = 1/RshLsbToVoltCoef();
See Also
RshLsbToVoltCoef()
Referenced by RshLsbToVolt().