Rsh API: RshTime Class Reference
RshTime Class Reference
Time store structure.
#include <RshTime.h>
Public Member Functions
RshTime ()
RshTime (U8 hours, U8 minutes, U8 seconds=0, U16 milliseconds=0, U16 microseconds=0)
RshTime (const RshTime &obj)
RshTime & operator= (const RshTime &obj)
bool operator== (const RshTime &obj) const
bool operator< (const RshTime &obj) const
bool operator!= (const RshTime &obj) const
bool operator> (const RshTime &obj) const
bool operator<= (const RshTime &obj) const
bool operator>= (const RshTime &obj) const
RshTime (double timeElapsed_s)
Convert elapsed time.
std::string toString (const std::string &format=std::string("hh:mm:ss:zzz.uuu")) const
Convert to string.
std::wstring toWString (const std::wstring &format=std::wstring(L"hh:mm:ss:zzz.uuu")) const
Convert to string.
U64 toMicroSeconds () const
Convert to microseconds.
void setHMS (U8 hours, U8 minutes, U8 seconds=0, U16 milliseconds=0, U16 microseconds=0)
Set structure time values.
void setFromElapsed (double timeElapsed_s)
Set structure time values.
U8 hours ()
Hours.
U8 minutes ()
Minuts.
U8 seconds ()
Seconds.
U16 milliSeconds ()
MilliSeconds.
U16 microSeconds ()
Microseconds.
Static Public Member Functions
static RshTime currentTime ()
Fill structure with current time information.
Friends
std::ostream & operator<< (std::ostream &out, const RshTime &obj)
Detailed Description
Time store structure.
Maximum value that can be stored in structure is 23h 59m 59s 999ms 999us
Constructor & Destructor Documentation
RshTime::RshTime ()
RshTime::RshTime (U8 hours, U8 minutes, U8 seconds = 0, U16 milliseconds = 0, U16 microseconds = 0)
References setHMS().
RshTime::RshTime (const RshTime & obj)
RshTime::RshTime (double timeElapsed_s)
Convert elapsed time.
Convert elapsed time in seconds (floating point) to hours, minutes, seconds, milliseconds and microseconds elapsed.
Parameters
[in] timeElapsed_s Time in seconds
Remarks
If timeElapsed_s is bigger or equal to 86400.0, time will be set to 23h 59m 59s 999ms 999us
References setFromElapsed().
Member Function Documentation
RshTime RshTime::currentTime () static
Fill structure with current time information.
This method fills the RshTime structure with current time values.
Returns
Filled RshTime structure.
U8 RshTime::hours () inline
Hours.
Referenced by setHMS().
U16 RshTime::microSeconds () inline
Microseconds.
U16 RshTime::milliSeconds () inline
MilliSeconds.
U8 RshTime::minutes () inline
Minuts.
Referenced by setHMS().
bool RshTime::operator!= (const RshTime & obj) const
bool RshTime::operator< (const RshTime & obj) const
bool RshTime::operator<= (const RshTime & obj) const
RshTime & RshTime::operator= (const RshTime & obj)
bool RshTime::operator== (const RshTime & obj) const
bool RshTime::operator> (const RshTime & obj) const
bool RshTime::operator>= (const RshTime & obj) const
U8 RshTime::seconds () inline
Seconds.
Referenced by setHMS().
void RshTime::setFromElapsed (double timeElapsed_s)
Set structure time values.
Parameters
[in] timeElapsed_s Time in seconds
Remarks
If timeElapsed_s is bigger or equal to 86400.0, time will be set to 23h 59m 59s 999ms 999us
Referenced by RshTime().
void RshTime::setHMS (U8 hours, U8 minutes, U8 seconds = 0, U16 milliseconds = 0, U16 microseconds = 0)
Set structure time values.
References hours(), minutes(), and seconds().
Referenced by RshTime().
U64 RshTime::toMicroSeconds () const
Convert to microseconds.
Returns
Current structure time in microseconds
std::string RshTime::toString (const std::string & format = std::string("hh:mm:ss:zzz.uuu")) const
Convert to string.
Convert to std::string, using format constant
hh - hours value
mm - minutes value
ss - seconds value
zzz - milliseconds value
uuu - microseconds value
For example, using "hh.mm" format string one can get something like "13.09"
Parameters
[in] format Default value is "hh:mm:ss:zzz.uuu"
Referenced by operator<<().
std::wstring RshTime::toWString (const std::wstring & format = std::wstring(L"hh:mm:ss:zzz.uuu")) const
Convert to string.
Convert to std::wstring, using format constant
hh - hours value
mm - minutes value
ss - seconds value
zzz - milliseconds value
uuu - microseconds value
For example, using "hh.mm" format string one can get something like "13.09"
Parameters
[in] format Default value is "hh:mm:ss:zzz.uuu"
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const RshTime & obj) friend
The documentation for this class was generated from the following files:
G:/SDK2/HEADERS/Include/RshTime.h
G:/SDK2/HEADERS/Include/RshTime.cpp