Rsh API: RshBufferType< T, dataCode > Class Template Reference
RshBufferType< T, dataCode > Class Template Reference
Template class for buffer construction.
#include <RshBufferType.h>
Public Types
typedef T value_type
Container data type.
typedef T & reference
Reference to data type.
typedef const T & const_reference
const reference to data type
typedef T * iterator
Iterator type. Pointer to data stored in container is used, because RshBufferType is array based.
typedef const T * const_iterator
const iterator type
typedef size_t size_type
size type
typedef ptrdiff_t difference_type
ptrdiff type
Public Member Functions
iterator begin ()
begin() method. Just return internal array pointer.
const_iterator begin () const
const begin() method. Just return internal array pointer.
iterator end ()
end() method. Return pointer to one-after-last element.
const_iterator end () const
const end() method. Return pointer to one-after-last element.
size_type size () const
Container size. Number of actual elements. Same as Size(), used for STL compatibility only.
size_type max_size () const
Maximum number of elements container can hold. Same as PSize(), used for STL compatibility only. We are not implementing "on the fly" allocation as std::vector, for example.
bool empty () const
Is container empty? Used for STL compatibility.
void swap (RshBufferType< T, dataCode > &obj)
Swap values of two containers.
RshBufferType (size_t bufferSize=32)
Constructor.
RshBufferType (const RshBufferType< T, dataCode > &obj)
Copy constructor.
~RshBufferType ()
Destructror.
U32 Allocate (size_t bufferSize=32)
Allocate memory for buffer data.
void Copy (const T *iptr, size_t psize, size_t size=0)
Copy data to buffer from memory location.
size_t CopyTo (T *iptr, size_t iptrSize) const
Copy data from buffer to memory location.
void Copy (const RshBufferType< T, dataCode > &srcBuffer)
Copy data from another buffer of the same type.
U32 SortAscending ()
Sort buffer elements in assending order.
U32 SortDescending ()
Sort buffer elements in descending order.
void Print (size_t size=0) const
Print buffer values in standart output.
U32 WriteBufferToFile (const char *fileName, size_t elements=0) const
Save buffer content to file.
U32 WriteBufferToFile (const std::string &fileName, size_t elements=0) const
U32 WriteBufferToFile (const wchar_t *fileName, size_t elements=0) const
U32 WriteBufferToFile (const std::wstring &fileName, size_t elements=0) const
U32 ReadBufferFromFile (const char *fileName, size_t elements=0)
Fill buffer with data from file.
U32 ReadBufferFromFile (const std::string &fileName, size_t elements=0)
U32 ReadBufferFromFile (const wchar_t *fileName, size_t elements=0)
U32 ReadBufferFromFile (const std::wstring &fileName, size_t elements=0)
size_t ByteSize () const
Get actual buffer data size.
size_t BytePSize () const
Get real buffer size in bytes.
size_t TypeSize () const
Get buffer element size.
size_t Size () const
Get actual buffer size in data elements.
size_t PSize () const
Get real buffer size in elements.
T & operator[] (size_t i)
const T & operator[] (size_t i) const
void Clear ()
Set actual buffer size to zero value.
void SetSize (size_t size)
Set actual buffer size.
RshBufferType< T, dataCode > & operator= (const RshBufferType< T, dataCode > &obj)
bool operator== (RshBufferType< T, dataCode > &obj) const
bool operator!= (RshBufferType< T, dataCode > &obj) const
bool operator< (RshBufferType< T, dataCode > &obj) const
bool operator> (RshBufferType< T, dataCode > &obj) const
bool operator<= (RshBufferType< T, dataCode > &obj) const
bool operator>= (RshBufferType< T, dataCode > &obj) const
U32 PushBack (T obj)
Add new element to buffer.
Public Member Functions inherited from RshBaseType
RshBaseType (const RshDataTypes type=rshTypeUndefined, const size_t typeSize=sizeof(RshBaseType))
Constructor.
const char * GetTypeName () const
Public Attributes
T * ptr
Direct pointer to allocated memory.
Public Attributes inherited from RshBaseType
const size_t _typeSize
Size of the data structure or class.
const RshDataTypes _type
Data type ID.
Friends
std::ostream & operator<< (std::ostream &out, const RshBufferType< T, dataCode > &obj)
Output buffer to std stream.
Additional Inherited Members
Static Public Member Functions inherited from RshBaseType
static const char * GetTypeName (const RshDataTypes typeCode)
Get type name as string literal.
Detailed Description
template<typename T, RshDataTypes dataCode>
class RshBufferType< T, dataCode >
Template class for buffer construction.
This template is used to construct data buffer container classes derived from RshBaseType.
Also contains some useful methods to work with data, such as sorting and saving to file.
Remarks
Data buffers created are used to pass data to polymorfic methods of SDK, such as IRshDevice::GetData() and so on.
See Also
RshBaseType
Examples:
GSPF-052PCI_Generate.cpp, GSPF-053USB_Generate.cpp, IRshDevice_DoubleFreqMode_EN.cpp, IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EN.cpp, IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EXT_EN.cpp, IRshDevice_Get_RSH_GET_DEVICE_IS_CAPABLE_EN.cpp, IRshDevice_GetData_DigitalInput_EN.cpp, LA-1.5PCI_Persistent.cpp, LA-1.5PCI_StartStop.cpp, LA-20USB_Persistent.cpp, LA-20USB_StartStop.cpp, LA-2M5PCI_Persistent.cpp, LA-2M5PCI_StartStop.cpp, LA-2USB_Persistent.cpp, LA-2USB_StartStop.cpp, LA-50USB_Persistent.cpp, LA-50USB_StartStop.cpp, LA-5Net_Persistent.cpp, LA-5Net_StartStop.cpp, LA-i24USB_Persistent.cpp, LA-i24USB_StartStop.cpp, LA-n10-12PCI_StartStop.cpp, LA-n10-12USB_StartStop.cpp, LA-n10M8-100PCI_StartStop.cpp, LA-n10M8-500PCI_StartStop.cpp, LA-n150PCI_Persistent.cpp, LA-n150PCI_StartStop.cpp, LA-n1USB_StartStop.cpp, LA-n20-12PCI_StartStop.cpp, LA-n2USB_StartStop.cpp, Leonardo2_Persistent.cpp, Leonardo2_StartStop.cpp, Python_Continuous.cpp, Python_StartStop.cpp, RshBufferType_STL_EN.cpp, RshError_EN.cpp, and Sirius_StartStop.cpp.
Member Typedef Documentation
template<typename T, RshDataTypes dataCode> typedef const T* RshBufferType< T, dataCode >::const_iterator
const iterator type
template<typename T, RshDataTypes dataCode> typedef const T& RshBufferType< T, dataCode >::const_reference
const reference to data type
template<typename T, RshDataTypes dataCode> typedef ptrdiff_t RshBufferType< T, dataCode >::difference_type
ptrdiff type
template<typename T, RshDataTypes dataCode> typedef T* RshBufferType< T, dataCode >::iterator
Iterator type. Pointer to data stored in container is used, because RshBufferType is array based.
template<typename T, RshDataTypes dataCode> typedef T& RshBufferType< T, dataCode >::reference
Reference to data type.
template<typename T, RshDataTypes dataCode> typedef size_t RshBufferType< T, dataCode >::size_type
size type
template<typename T, RshDataTypes dataCode> typedef T RshBufferType< T, dataCode >::value_type
Container data type.
Constructor & Destructor Documentation
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::RshBufferType (size_t bufferSize = 32)
Constructor.
References RshBufferType< T, dataCode >::ptr.
template<typename T, RshDataTypes dataCode> RshBufferType< T, dataCode >::RshBufferType (const RshBufferType< T, dataCode > & obj)
Copy constructor.
References RshBufferType< T, dataCode >::Copy(), and RshBufferType< T, dataCode >::ptr.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::~RshBufferType ()
Destructror.
Member Function Documentation
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::Allocate (size_t bufferSize = 32)
Allocate memory for buffer data.
Parameters
[in] bufferSize Desired size of buffer (elements number). If system will fail to allocate memory, error code will be returned and RshBufferType::PSize() field will be equal to zero.
Returns
RSH_API_SUCCESS or error code.
Use this method to set buffer size you need and allocate memory for data. After successfull call of this method RshBufferType::PSize() will be equal to buffer size (number of elements), and RshBufferType::ptr will point to allocated memory.
Remarks
If buffer size before call of this method was different from bufferSize parameter passes, old memory block will be delited, and all data will be lost.
Examples:
LA-1.5PCI_Persistent.cpp, LA-20USB_Persistent.cpp, LA-2M5PCI_Persistent.cpp, LA-2USB_Persistent.cpp, LA-50USB_Persistent.cpp, LA-5Net_Persistent.cpp, LA-i24USB_Persistent.cpp, LA-n150PCI_Persistent.cpp, Leonardo2_Persistent.cpp, Python_Continuous.cpp, and RshError_EN.cpp.
References RSH_API_BUFFER_ALLOCATIONZEROSIZE, RSH_API_MEMORY_ALLOCATIONERROR, and RSH_API_SUCCESS.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::iterator RshBufferType< T, dataCode >::begin ()
begin() method. Just return internal array pointer.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::const_iterator RshBufferType< T, dataCode >::begin () const
const begin() method. Just return internal array pointer.
template<typename T , RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::BytePSize () const
Get real buffer size in bytes.
Returns
Physical size of a buffer in bytes.
Using this method one can obtain physical size of a buffer (RshBufferType::BytePSize() elements) in bytes.
Examples:
LA-1.5PCI_Persistent.cpp, LA-20USB_Persistent.cpp, LA-2M5PCI_Persistent.cpp, LA-2USB_Persistent.cpp, LA-50USB_Persistent.cpp, LA-5Net_Persistent.cpp, LA-i24USB_Persistent.cpp, LA-n150PCI_Persistent.cpp, and Leonardo2_Persistent.cpp.
template<typename T , RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::ByteSize () const
Get actual buffer data size.
Returns
Size of actual data in buffer in bytes.
Using this method one can obtain size of actual data (RshBufferType::Size() elements) in bytes.
template<typename T , RshDataTypes dataCode> void RshBufferType< T, dataCode >::Clear ()
Set actual buffer size to zero value.
Remarks
Good to use before an invoke of IRshDevice::GetData().
template<typename T, RshDataTypes dataCode> void RshBufferType< T, dataCode >::Copy (const T * iptr, size_t psize, size_t size = 0)
Copy data to buffer from memory location.
Parameters
[in] iptr Pointer to memory block from where data will be copied to buffer.
[in] psize Physical size (in samples) of memory block pointed by iptr parameter.
[in] size How many samples need to be copied from iptr memory location.
If zero, maximum avaliable samples will be copied.
Use this method to fill buffer with data. If allocated buffer size is less than size, only part of data will be copied to buffer. Always check RshBufferType::Size() after operation complition to check how many elements buffer contain.
Referenced by RshBufferType< T, dataCode >::RshBufferType(), RshCopyStringToBuffer(), RshInitADC::RshInitADC(), RshInitDMA::RshInitDMA(), and RshInitMemory::RshInitMemory().
template<typename T, RshDataTypes dataCode> void RshBufferType< T, dataCode >::Copy (const RshBufferType< T, dataCode > & srcBuffer)
Copy data from another buffer of the same type.
Parameters
[in] srcBuffer Buffer of the same type from which data will be copied to caller buffer.
Using this method one can fill buffer with data from another buffer.
Remarks
No memory allocation is performed! If destination buffer psize is smaller than source buffer size, only psize first elements will be copied.
If you want create identical buffer, use copy constructor (dstBuffer = srcBuffer).
References RshBufferType< T, dataCode >::ptr.
template<typename T, RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::CopyTo (T * iptr, size_t iptrSize) const
Copy data from buffer to memory location.
Parameters
[in,out] iptr Address of memory block where data from buffer will be placed.
[in] iptrSize Maximum size (in samples) of memory available for data.
Returns
Number of buffer elements copied to destination memory.
Copy data block from buffer to memory block with address specified in iptr parameter.
If buffer size is smaller than iptrSize, only RshBufferType::PSize() elements will be copied.
Remarks
This method always try to copy maximum elements availiable. If you need copy only, say, ten elements to destination memory, specify parameter iptrSize=10.
template<typename T , RshDataTypes dataCode> bool RshBufferType< T, dataCode >::empty () const
Is container empty? Used for STL compatibility.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::iterator RshBufferType< T, dataCode >::end ()
end() method. Return pointer to one-after-last element.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::const_iterator RshBufferType< T, dataCode >::end () const
const end() method. Return pointer to one-after-last element.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::size_type RshBufferType< T, dataCode >::max_size () const
Maximum number of elements container can hold. Same as PSize(), used for STL compatibility only. We are not implementing "on the fly" allocation as std::vector, for example.
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator!= (RshBufferType< T, dataCode > & obj) const
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator< (RshBufferType< T, dataCode > & obj) const
References RshBufferType< T, dataCode >::ptr.
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator<= (RshBufferType< T, dataCode > & obj) const
template<typename T, RshDataTypes dataCode> RshBufferType< T, dataCode > & RshBufferType< T, dataCode >::operator= (const RshBufferType< T, dataCode > & obj)
References RshBufferType< T, dataCode >::ptr.
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator== (RshBufferType< T, dataCode > & obj) const
References RshBufferType< T, dataCode >::ptr.
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator> (RshBufferType< T, dataCode > & obj) const
template<typename T, RshDataTypes dataCode> bool RshBufferType< T, dataCode >::operator>= (RshBufferType< T, dataCode > & obj) const
template<typename T , RshDataTypes dataCode> T & RshBufferType< T, dataCode >::operator[] (size_t i)
template<typename T , RshDataTypes dataCode> const T & RshBufferType< T, dataCode >::operator[] (size_t i) const
template<typename T , RshDataTypes dataCode> void RshBufferType< T, dataCode >::Print (size_t size = 0) const
Print buffer values in standart output.
Parameters
[in] size Number of elements to print. If zero (default) value is passed, all available elements will be printed.
Output buffer content to console. If size parameters is specified, only first size elements will be printed. Otherwise, RshBufferType::Size() elements will be printed (for initialized buffer with size>0). If RshBufferType::Size() is equal to zero too, all data (RshBufferType::PSize()) will be printed.
template<typename T , RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::PSize () const
Get real buffer size in elements.
Returns
Physical size of a buffer in elements.
Using this method one can obtain physical size of a buffer (RshBufferType::psize field) in elements.
Referenced by RshCopyStringToBuffer().
template<typename T, RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::PushBack (T obj)
Add new element to buffer.
Adds new element to buffer end and increase its size by one. If there is no more space left in buffer (see RshBufferType::PSize()), error code will be returned
Returns
RSH_API_SUCCESS or error code
Parameters
[in] obj Value to push in buffer.
References RSH_API_BUFFER_INSUFFICIENTSIZE, and RSH_API_SUCCESS.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::ReadBufferFromFile (const char * fileName, size_t elements = 0)
Fill buffer with data from file.
Parameters
[in] fileName Path to the file which will be used as data source to fill the buffer.
[in] elements Number of elements to read from file. If zero, all file content will be placed in buffer.
Returns
RSH_API_SUCCESS or error code.
Using this method, one can fill buffer with data stored in binary file.
Remarks
Memory will be allocated automaticaly to store data in buffer, if current psize is not enough. If not empty buffer is used for this operation, its content will be lost.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::ReadBufferFromFile (const std::string & fileName, size_t elements = 0)
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::ReadBufferFromFile (const wchar_t * fileName, size_t elements = 0)
Warning
This method will have problems with non-latin characters in current SDK release
Todo:
Fix character encoding issues.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::ReadBufferFromFile (const std::wstring & fileName, size_t elements = 0)
Warning
This method will have problems with non-latin characters in current SDK release
Todo:
Fix character encoding issues.
template<typename T , RshDataTypes dataCode> void RshBufferType< T, dataCode >::SetSize (size_t size)
Set actual buffer size.
Sometimes it is convenient to reuse buffer without memory allocation, that can be performance hit. Setting buffer size value manualy one can tell users of that buffer, that buffer only contains Size() elements of useful data.
Parameters
[in] size Actual buffer size to set
Remarks
Most internal methods in RshApi use this information when iterating over buffers. If passed size is more than buffer PSize(), it will be truncated.
Examples:
IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EN.cpp, and IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EXT_EN.cpp.
template<typename T , RshDataTypes dataCode> RshBufferType< T, dataCode >::size_type RshBufferType< T, dataCode >::size () const
Container size. Number of actual elements. Same as Size(), used for STL compatibility only.
template<typename T , RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::Size () const
Get actual buffer size in data elements.
Returns
Size of actual data in buffer in elements.
Using this method one can obtain size of actual data (field RshBufferType::size) in elements.
Examples:
IRshDevice_DoubleFreqMode_EN.cpp, IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EN.cpp, IRshDevice_Get_RSH_GET_DEVICE_BASE_LIST_EXT_EN.cpp, IRshDevice_GetData_DigitalInput_EN.cpp, and Python_Continuous.cpp.
Referenced by RshInitADC::ActiveChannelsNumber(), and operator<<().
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::SortAscending ()
Sort buffer elements in assending order.
Returns
RSH_API_SUCCESS or error code.
This method use std::sort algorithm to sort elements in assending orfer.
References RSH_API_BUFFER_NOTINITIALIZED, and RSH_API_SUCCESS.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::SortDescending ()
Sort buffer elements in descending order.
Returns
RSH_API_SUCCESS or error code.
This method use std::sort algorithm to sort elements in descending orfer.
References RSH_API_BUFFER_NOTINITIALIZED, and RSH_API_SUCCESS.
template<typename T, RshDataTypes dataCode> void RshBufferType< T, dataCode >::swap (RshBufferType< T, dataCode > & obj)
Swap values of two containers.
References RshBufferType< T, dataCode >::ptr.
template<typename T , RshDataTypes dataCode> size_t RshBufferType< T, dataCode >::TypeSize () const
Get buffer element size.
Returns
Size of buffer element in bytes.
Using this method one can obtain size of buffer element in bytes.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::WriteBufferToFile (const char * fileName, size_t elements = 0) const
Save buffer content to file.
Parameters
[in] fileName Path to file where buffer must be written.
[in] elements Number of elements to write. If passed elements == 0, actual number of elements to write will be Size() if buffer Size() > 0 or PSize() otherwise.
Returns
RSH_API_SUCCESS or error code.
Using this method, one can write RshBufferType::Size() elements to file specified by fileName.
Examples:
LA-1.5PCI_Persistent.cpp, LA-20USB_Persistent.cpp, LA-2M5PCI_Persistent.cpp, LA-2USB_Persistent.cpp, LA-50USB_Persistent.cpp, LA-5Net_Persistent.cpp, LA-i24USB_Persistent.cpp, LA-n150PCI_Persistent.cpp, Leonardo2_Persistent.cpp, and RshError_EN.cpp.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::WriteBufferToFile (const std::string & fileName, size_t elements = 0) const
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::WriteBufferToFile (const wchar_t * fileName, size_t elements = 0) const
Warning
This method will have problems with non-latin characters in current SDK release
Todo:
Fix character encoding issues.
template<typename T , RshDataTypes dataCode> U32 RshBufferType< T, dataCode >::WriteBufferToFile (const std::wstring & fileName, size_t elements = 0) const
Warning
This method will have problems with non-latin characters in current SDK release
Todo:
Fix character encoding issues.
Friends And Related Function Documentation
template<typename T, RshDataTypes dataCode> std::ostream& operator<< (std::ostream & out, const RshBufferType< T, dataCode > & obj) friend
Output buffer to std stream.
This overloaded operation only prints first 32 elements, or less, if buffer is smaller. If you need to print large buffer, or specify exact number of elements to print, use Print() method.
Member Data Documentation
template<typename T, RshDataTypes dataCode> T* RshBufferType< T, dataCode >::ptr
Direct pointer to allocated memory.
One can use this pointer to access to buffer data (there is also overloaded [] operator, but this method is faster - for long buffers its preferable).
Warning
Do not delete or change this pointer! All operations with memory allocation and release must be performed using class methods. This pointer is set as public only because performance issuses.
Also, always refer to RshBufferType::PSize() when indexing.
Examples:
IRshDevice_DoubleFreqMode_EN.cpp, LA-1.5PCI_Persistent.cpp, LA-20USB_Persistent.cpp, LA-2M5PCI_Persistent.cpp, LA-2USB_Persistent.cpp, LA-50USB_Persistent.cpp, LA-5Net_Persistent.cpp, LA-i24USB_Persistent.cpp, LA-n150PCI_Persistent.cpp, and Leonardo2_Persistent.cpp.
Referenced by RshInitADC::ActiveChannelsNumber(), RshBufferType< T, dataCode >::Copy(), RshBufferType< T, dataCode >::operator<(), RshBufferType< T, dataCode >::operator=(), RshBufferType< T, dataCode >::operator==(), RshBufferType< T, dataCode >::RshBufferType(), and RshBufferType< T, dataCode >::swap().
The documentation for this class was generated from the following files:
G:/SDK2/HEADERS/Include/RshBufferType.h
G:/SDK2/HEADERS/Include/RshBufferType.cpp