Rsh API: RshSynchroChannel Struct Reference
RshSynchroChannel Struct Reference
External trigger channel parameters.
#include <RshSynchroChannel.h>
Public Types
enum Control {
FilterOff = 0x0, Resist1MOhm = 0x0, DC = 0x0, FilterLow = 0x1,
FilterHigh = 0x2, AC = 0x4, Resist50Ohm = 0x8
}
Channel flag list.
Public Member Functions
RshSynchroChannel ()
RshSynchroChannel & operator= (const RshSynchroChannel &obj)
bool operator== (RshSynchroChannel &obj) const
bool operator!= (RshSynchroChannel &obj) const
void SetDefaultPatameters ()
Set channel parameters to default values.
void SetFilterLow (bool on=true)
Set or remove RshSynchroChannel::FilterLow flag.
void SetFilterHigh (bool on=true)
Set or remove RshSynchroChannel::FilterHigh flag.
void SetInputAC (bool on=true)
Set or remove RshSynchroChannel::AC flag.
void SetInputDC (bool on=true)
Set or remove RshSynchroChannel::DC flag.
void SetResist50Ohm (bool on=true)
Set or remove RshSynchroChannel::Resist50Ohm flag.
void SetResist1MOhm (bool on=true)
Set or remove RshSynchroChannel::Resist1MOhm flag.
bool IsFilterHighActive () const
Check RshChannel::FilterHigh flag.
bool IsFilterLowActive () const
Check RshChannel::FilterLow flag.
bool IsInputACActive () const
Check RshChannel::AC flag.
bool IsInputDCActive () const
Check RshChannel::DC flag.
bool IsResist50OhmActive () const
Check RshChannel::Resist50Ohm flag.
bool IsResist1MOhmActive () const
Check RshChannel::Resist1MOhm flag.
Public Member Functions inherited from RshBaseType
RshBaseType (const RshDataTypes type=rshTypeUndefined, const size_t typeSize=sizeof(RshBaseType))
Constructor.
const char * GetTypeName () const
Public Attributes
U32 gain
Gain coefficient.
U32 control
Additional flags.
Public Attributes inherited from RshBaseType
const size_t _typeSize
Size of the data structure or class.
const RshDataTypes _type
Data type ID.
Friends
std::ostream & operator<< (std::ostream &out, const RshSynchroChannel &obj)
Additional Inherited Members
Static Public Member Functions inherited from RshBaseType
static const char * GetTypeName (const RshDataTypes typeCode)
Get type name as string literal.
Detailed Description
External trigger channel parameters.
This structure is similar to RshChannel, but used to setup external trigger channel.
Member Enumeration Documentation
enum RshSynchroChannel::Control
Channel flag list.
Additional channel parameters that can be passed in RshSynchroChannel::control field.
Enumerator
FilterOff
Turn OFF filters for external trigger channel.
Mutually exclusive with RshSynchroChannel::FilterLow and RshSynchroChannel::FilterHigh
Resist1MOhm
Set 1MOhm resist for external trigger channel.
Mutually exclusive with RshSynchroChannel::Resist50Ohm
DC
Set input to DC mode.
Mutually exclusive with RshSynchroChannel::AC
FilterLow
Turn on low pass filter for external trigger channel.
Mutually exclusive with RshSynchroChannel::FilterOff and RshSynchroChannel::FilterHigh
See Also
RSH_CAPS_DEVICE_EXT_SYNC_FILTER_LOW
FilterHigh
Turn on high pass filter for external trigger channel.
Mutually exclusive with RshSynchroChannel::FilterOff and RshSynchroChannel::FilterLow
See Also
RSH_CAPS_DEVICE_EXT_SYNC_FILTER_HIGH
AC
Set input to AC mode.
Mutually exclusive with RshSynchroChannel::DC
Resist50Ohm
Set 50Ohm resist for channel.
Mutually exclusive with RshSynchroChannel::Resist1MOhm
Constructor & Destructor Documentation
RshSynchroChannel::RshSynchroChannel ()
Member Function Documentation
bool RshSynchroChannel::IsFilterHighActive () const
Check RshChannel::FilterHigh flag.
References control, and FilterHigh.
bool RshSynchroChannel::IsFilterLowActive () const
Check RshChannel::FilterLow flag.
References control, and FilterLow.
bool RshSynchroChannel::IsInputACActive () const
Check RshChannel::AC flag.
References AC, and control.
Referenced by IsInputDCActive().
bool RshSynchroChannel::IsInputDCActive () const
Check RshChannel::DC flag.
References IsInputACActive().
bool RshSynchroChannel::IsResist1MOhmActive () const
Check RshChannel::Resist1MOhm flag.
References IsResist50OhmActive().
bool RshSynchroChannel::IsResist50OhmActive () const
Check RshChannel::Resist50Ohm flag.
References control, and Resist50Ohm.
Referenced by IsResist1MOhmActive().
bool RshSynchroChannel::operator!= (RshSynchroChannel & obj) const
References operator==().
RshSynchroChannel & RshSynchroChannel::operator= (const RshSynchroChannel & obj)
References control, and gain.
bool RshSynchroChannel::operator== (RshSynchroChannel & obj) const
References control, and gain.
Referenced by operator!=().
void RshSynchroChannel::SetDefaultPatameters ()
Set channel parameters to default values.
gain = 1; control = 0;
Examples:
RshInitMemroySynchroChannel_EN.cpp.
References control, and gain.
void RshSynchroChannel::SetFilterHigh (bool on = true)
Set or remove RshSynchroChannel::FilterHigh flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::FilterHigh flag will automaticaly remove RshSynchroChannel::FilterLow flag. Removing RshSynchroChannel::FilterHigh flag will automaticaly remove BOTH RshSynchroChannel::FilterHigh and RshSynchroChannel::FilterLow, that is equal to setting RshSynchroChannel::FilterOff flag.
Examples:
RshInitMemroySynchroChannel_EN.cpp.
References control, FilterHigh, and FilterLow.
void RshSynchroChannel::SetFilterLow (bool on = true)
Set or remove RshSynchroChannel::FilterLow flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::FilterLow flag will automaticaly remove RshSynchroChannel::FilterHigh flag. Removing RshSynchroChannel::FilterLow flag will automaticaly remove BOTH RshSynchroChannel::FilterLow and RshSynchroChannel::FilterHigh flags, that is equal to setting RshSynchroChannel::FilterOff flag.
References control, FilterHigh, and FilterLow.
void RshSynchroChannel::SetInputAC (bool on = true)
Set or remove RshSynchroChannel::AC flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::AC flag automaticaly remove RshSynchroChannel::DC flag and vise versa.
Examples:
RshInitMemroySynchroChannel_EN.cpp.
References AC, and control.
Referenced by SetInputDC().
void RshSynchroChannel::SetInputDC (bool on = true)
Set or remove RshSynchroChannel::DC flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::DC flag automaticaly remove RshSynchroChannel::AC flag and vise versa.
References SetInputAC().
void RshSynchroChannel::SetResist1MOhm (bool on = true)
Set or remove RshSynchroChannel::Resist1MOhm flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::Resist1MOhm flag automaticaly remove RshSynchroChannel::Resist50Ohm flag and vise versa.
Examples:
RshInitMemroySynchroChannel_EN.cpp.
References SetResist50Ohm().
void RshSynchroChannel::SetResist50Ohm (bool on = true)
Set or remove RshSynchroChannel::Resist50Ohm flag.
Parameters
[in] on If true, flag will be set, if false flag will be removed. Setting RshSynchroChannel::Resist50Ohm flag automaticaly remove RshSynchroChannel::Resist1MOhm flag and vise versa.
References control, and Resist50Ohm.
Referenced by SetResist1MOhm().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const RshSynchroChannel & obj) friend
Member Data Documentation
U32 RshSynchroChannel::control
Additional flags.
'OR' Combination of RshSynchroChannel::Control enum elements. If flag set is not supported by device, it will be ignored.
Remarks
By default, this parameter is equal to zero, which corresponds to following flag combination:
RshSynchroChannel::FilterOff | RshSynchroChannel::Resist1MOhm | RshSynchroChannel::DC
Referenced by IsFilterHighActive(), IsFilterLowActive(), IsInputACActive(), IsResist50OhmActive(), operator<<(), operator=(), operator==(), SetDefaultPatameters(), SetFilterHigh(), SetFilterLow(), SetInputAC(), and SetResist50Ohm().
U32 RshSynchroChannel::gain
Gain coefficient.
Gain coefficient to use for external trigger channel.
Remarks
One can get list of availiable gain coefficients, using IRshDevice::Get() method with RSH_GET_DEVICE_EXT_SYNC_GAINLIST parameter.
Examples:
RshInitMemroySynchroChannel_EN.cpp.
Referenced by operator<<(), operator=(), operator==(), and SetDefaultPatameters().
The documentation for this struct was generated from the following files:
G:/SDK2/HEADERS/Include/RshSynchroChannel.h
G:/SDK2/HEADERS/Include/RshSynchroChannel.cpp